Add prometheus variable for datasource
grafana/xk6-output-prometheus-remote pull request #114
Opened 2023-03-27 19:20 UTC by 7olstoy

These values of datasource were hardcoded and does not use the variable.

2023-03-27 19:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-output-prometheus-remote?pullRequest=114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-output-prometheus-remote?pullRequest=114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-output-prometheus-remote?pullRequest=114) it.</sub>

2023-03-28 12:59 UTC, javaducky requested changes
Hi @7olstoy! Thank you for your update. Looks like you're missing the definition for the `DS_PROMETHEUS` variable.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/944496/228241472-031bfe08-c4d4-41a1-bff1-c0fa2e5847f0.png">

2023-04-01 23:19 UTC, 7olstoy commented
Hey @javaducky, thank you for your catch!
Added the variable and the same requires as already exist in another files.

2023-04-03 13:06 UTC, javaducky approved these changes
LGTM! Thank you for fix.

2023-04-03 13:06 UTC, merged