Fix 32-bit build
grafana/xk6-output-prometheus-remote pull request #158
Opened 2023-10-31 20:01 UTC by mem

When trying to build for 32-bit ARM (linux/arm), you get:

```
pkg/remote/client.go:120:35: cannot use 0xffffffff (untyped int constant 4294967295) as int value in argument to fmt.Errorf (overflows)
```

Pass the constant as unsigned 64-bit integer, which is what the underlying snappy code is doing (it's casting the argument to an uint64 and comparing against 0xffffffff, which in Go means it's comparing against uint64(0xffffffff)). Since this is just an error message, it shouldn't matter, but let's be consistent.

2023-10-31 20:04 UTC, mem commented
Sorry about recreating the PR instead of reopening the old one (#132). My bad.

I reworded the commit message to reflect the fact that this is not specific to ARM.

The reason why I would like to have this is because I would like to run k6 on linux/arm (Raspberry Pi and whatnot).

2023-11-08 17:35 UTC, codebien requested changes
Hey @mem,
I think my comment on the previous PR https://github.com/grafana/xk6-output-prometheus-remote/pull/132#discussion_r1259401503 is still valid, can you take a look into it, please?

2023-12-19 14:53 UTC, codebien approved these changes

2023-12-19 14:53 UTC, mstoykov approved these changes

2023-12-19 15:00 UTC, merged