feat: Add SigV4 support
grafana/xk6-output-prometheus-remote pull request #161
Opened 2024-02-02 10:09 UTC by rybbchao

Add SigV4 support for #93.

Environment variables:

- `K6_PROMETHEUS_RW_SIGV4_AUTH`: Enable **SigV4** for **AWS Managed Prometheus**.
- `K6_PROMETHEUS_RW_SIGV4_REGION`: AWS region where the workspace is.
- `K6_PROMETHEUS_RW_SIGV4_ACCESS_KEY`: AWS access key.
- `K6_PROMETHEUS_RW_SIGV4_SECRET_KEY`: AWS secret key.
- `K6_PROMETHEUS_RW_SIGV4_PROFILE`: AWS profile to use.
- `K6_PROMETHEUS_RW_SIGV4_ROLE_ARN`: AWS role ARN to assume.

2024-02-02 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-output-prometheus-remote?pullRequest=161) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-output-prometheus-remote?pullRequest=161) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-output-prometheus-remote?pullRequest=161) it.</sub>

2024-02-08 16:02 UTC, mstoykov commented
Looking at teh amount of dependancies this pulls in ... I am concerned.

I did a quick check and this adds 7mb on top of k6 for this one authentication. +Every security alert we get about all of those dependancies.

GIven that this currently goes in k6 core I really would prefer not to merge this.

Some quick googling shows that there are ways to get the authenticaiton without pulling in the whole aws sdk and I would recommend we actually go down this route

https://gist.github.com/anandkunal/b67eb94454b77cfc2b50026989586cc0 

cc @codebien

2024-02-08 16:24 UTC, codebien requested changes
I agree, @rybbchao would you be interested in trying the path suggested by @mstoykov?

2024-07-03 13:46 UTC, codebien commented
Hey @rybbchao,
I'm going to close this issue as it seems is not under active development. Feel free to re-open if you find the time to re-work the changes.

Thanks for your contribution :bow:

2024-07-03 13:46 UTC, closed without merging