adding client certificate and key
grafana/xk6-output-prometheus-remote pull request #90
Opened 2022-12-19 09:53 UTC by raoel

hey there,

for our case we needed to add a client certificate and key to the configuration - I'd like to upstream my changes.

I hope this passes your standards - I've modified existing unit tests for configuration (I didn't do a full integration test with certificates because that would make the testing setup a lot more complex)

2022-12-19 09:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-output-prometheus-remote?pullRequest=90) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-output-prometheus-remote?pullRequest=90) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-output-prometheus-remote?pullRequest=90) it.</sub>

2022-12-19 13:46 UTC, codebien commented
Hi @raoel,
thanks for your contribution. :bow: 

Can you sign the CLA, please? We need it to accept the contribution.

2022-12-20 10:55 UTC, raoel commented
> Hi @raoel, thanks for your contribution. bow
> 
> Can you sign the CLA, please? We need it to accept the contribution.

had to get permission from my employer :-) should be fixed.

2022-12-22 09:59 UTC, codebien commented
Hi @raoel,
can you better explain your use case and how you're configuring the remote write, please?

Are you using a self-signed certificate or an internal CA? You should not share the pair with the client but just provide the CA file. https://prometheus.io/docs/guides/tls-encryption/#testing

2022-12-27 09:41 UTC, raoel commented
hello (sorry for the delay... things go slow - it's been christmas here too ;-)  )

We have mutual TLS, so instead of providing the client with a username/password we need to provide the client with it's key and certificate to be able to authenticate. So, as far as I know, the client really need the pair.

2023-08-16 16:26 UTC, codebien requested changes
Hey @raoel, sorry for the late reply :pray: Thanks again for your contribution. I've take a quick look and I've added some comments.

I didn't test yet it on a real setup, I will be on PTO for the rest of the week. I will do more tests on Monday.

2023-08-16 16:26 UTC, codebien commented on README.md
> +
We should document that in the case a different CA is required then the relative operating systems' storage shouid be used for providing the custom CA.

2023-08-16 16:26 UTC, codebien commented on pkg/remotewrite/config.go
> +	if conf.ClientCertificate.Valid && conf.ClientCertificateKey.Valid {
I would prefer if we skip the assignment if Insecure is set to `true`.

2023-08-16 16:26 UTC, codebien commented on pkg/remotewrite/config.go
> +	}
Are these duplicated lines?

2023-08-16 16:26 UTC, codebien commented on pkg/remotewrite/config.go
> +	}
Are they duplicated?

2023-08-16 16:26 UTC, codebien commented on pkg/remotewrite/config_test.go
> +		//"Arg":  {arg: "username=user1,password=pass1"},
```suggestion
```

2023-08-16 16:26 UTC, codebien commented on pkg/remotewrite/config_test.go
> +func TestOptionClientCertificate(t *testing.T) {
Duplicated?

2023-09-20 12:53 UTC, codebien approved these changes
Hey @raoel, thanks again for the contribution. I merge this PR on a development branch where we will do some polish of the feature then we will merge on the main branch. I will make sure to preserve you as the author/contributor of your commits.

2023-09-21 10:15 UTC, codebien commented
Unfortunately, this branch contains conflicts and we can't push here because the PR is generated from a fork. Going to continue the work on #143 preserving the commit history and the original author.

2023-09-21 10:15 UTC, closed without merging